import eslintConfigPrettier from "eslint-config-prettier";
import eslintPluginPrettier from "eslint-plugin-prettier";

export default [
  {
    files: ["src/**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Date: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        React: "readonly",
        useState: "readonly",
        useEffect: "readonly",
        useCallback: "readonly",
        useRef: "readonly",
        useMemo: "readonly",
        useContext: "readonly",
        useReducer: "readonly",
        useId: "readonly",
        useTransition: "readonly",
        useDeferredValue: "readonly",
        useSyncExternalStore: "readonly",
        createContext: "readonly",
        useQuery: "readonly",
        useMutation: "readonly",
        useQueryClient: "readonly",
        QueryClient: "readonly",
        QueryClientProvider: "readonly",
      },
    },
    plugins: {
      prettier: eslintPluginPrettier,
    },
    rules: {
      "prettier/prettier": "error",
      "no-unused-vars": "warn",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "no-alert": "warn",
      "eqeqeq": ["error", "always"],
      "curly": ["error", "multi-line"],
      "prefer-const": "error",
      "no-var": "error",
      "object-shorthand": "error",
      "prefer-template": "warn",
      "no-template-curly-in-string": "off",
      "no-throw-literal": "error",
      "valid-typeof": "error",
      "no-return-await": "error",
      "prefer-promise-reject-errors": "error",
      "require-atomic-updates": "off",
      "no-restricted-globals": "off",
      "no-self-compare": "error",
      "no-duplicate-imports": "error",
      "no-multi-spaces": "error",
      "comma-dangle": ["error", "always-multiline"],
      "indent": ["error", 2, { SwitchCase: 1 }],
      "max-len": ["error", { code: 100 }],
      "linebreak-style": ["error", "unix"],
      "semi": ["error", "always"],
      "quotes": ["error", "single", { avoidEscape: true }],
      "arrow-parens": ["error", "always"],
      "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0 }],
      "no-trailing-spaces": "error",
      "no-tabs": "error",
      "computed-property-spacing": ["error", "never"],
      "space-before-function-paren": ["error", "never"],
      "no-param-reassign": "error",
      "no-continue": "off",
      "no-plusplus": "off",
      "no-await-in-loop": "off",
      "max-lines": ["error", 500],
    },
  },
  eslintConfigPrettier,
  // Override for legitimate page components that have many options/data tables
  {
    files: ["src/pages/SuperAdminDashboard.jsx", "src/pages/Sales.jsx", "src/pages/Customers.jsx", "src/pages/SuperAdminOrganizations.jsx", "src/pages/Stock.jsx"],
    rules: {
      "max-lines": "off",
    },
  },
];